### ISSUE TITLE
No es necesario esto, ya que en el index no se debe especificar un id en concreto, ya que aquí se globaliza.

### ISSUE THREAD

**Issue by DjMarte** [IsaacCoste/TecnicosRegistros#5]
https://github.com/IsaacCoste/TecnicosRegistros/blob/03f352452fe35f8a32033f0fdf606e2c90b2d3ae/Components/Pages/TecnicosPages/Index.razor#L2

**Comment by IsaacCoste** [comment]
Lo corregi en el anterios commint #4
